### ISSUE TITLE
InitializerPlugin documentation

### ISSUE THREAD

**Issue by amihab** [ovh/utask#150]
Hi,

I am trying to implement an InitializerPlugin for http header token authentication.
I find documentation not clear enough and really struggling with this one.
The documentation of the plugins us much more clearer and lots of examples exist.
Would really appreciate simple example or additional information for the documentation.

**Comment by rbeuque74** [comment]
Hello @amihab,
You can find in the PR #153 an example to help you developing your custom init plugin.
Feel free to come back to us if it requires more explaination.

Romain
