### ISSUE TITLE
More flexible subtask plugin

### ISSUE THREAD

**Issue by rclsilver** [ovh/utask#184]
**Is your feature request related to a problem? Please describe.**
When uTask invokes an other template as a subtask, the step is not very relevant. Its state is SERVER_ERROR while the template is running and if watchers list is not defined, it is a sort of black-box for them.

**Describe the solution you'd like**
We could be execute a subtask with two modes:

1. Mode 1: With the current behavior, but with a better status (https://github.com/ovh/utask/pull/181) and a easy way to view subtask details (a link or something like that)

1. Mode 2: Subtask steps could be included in the main template (recursive behavior)  and with this mode, subtask mecanism is hidden for the users.

**Describe alternatives you've considered**
In all cases, an option which define watchers list with parent watchers list could be fine, particullary when we have subtasks of subtasks.

**Comment by loopfz** [comment]
Thanks for the suggestion.

For subtasks:
We're working on improving the user interface to provide a list with status + details link for all the subtasks, in the parent task details page. Should be available in the next version.

The recursive feature you describe will not work as-is, some global context (e.g. inputs) will conflict.

For watchers, see the suggestion in #188, if that looks good to everyone involved in may be a part of the next release too.
