### ISSUE TITLE
Using utask as a task manager for people.

### ISSUE THREAD

**Issue by pallid** [ovh/utask#292]
Hello, thanks for the wonderful utask

**Is your feature request related to a problem? Please describe.**
We want to try using utask as a task manager for people. For example, the negotiation of contracts or the execution of a high-level task by several executors (subtasks). Do you have an experience of using utask for such cases?

**Comment by loopfz** [comment]
Thank you for your interest.

Supporting human processes is one of the features of utask yes.

I personally have not used it for 100% human-implemented workflows, but I have often implemented workflows where 1 of the steps was human/manual.
This is typically done by having this step be of type `subtask`, using a task template with no steps, and `resolver_inputs` configured so the human can enter the values via a form in the UI.
