### ISSUE TITLE
Return output from subtask

### ISSUE THREAD

**Issue by mtereshenko** [ovh/utask#293]
Hello.
How I can get result's subtask in main task, like as state, result and e.t.c.?

Sorry, but I didn't find example in manual and test templates.

All the best, Michael

**Comment by rbeuque74** [comment]
Hello,

When using the executor `subtask`, you will receive the `result` of the sub tasks that run.
To declare what will be the composition of your `result`, you can declare it in the subtask template.

You will find an example of the declaration here: https://github.com/ovh/utask/blob/master/examples/templates/hello-world-now.yaml#L7-L9

The return of the `subtask` executor is declared here: https://github.com/ovh/utask/blob/master/pkg/plugins/builtin/subtask/README.md#return

I will close this issue, if you have further question, feel free to open it !
Thanks
Romain

**Comment by mtereshenko** [comment]
Romain, thank you, very much for answer!

I have one question. 
How should I declare an object in the main task to get data from the sub task into it?
Sorry, but I don't understand :(

All the best, Michael
