### ISSUE TITLE
docker-compose exit 1

### ISSUE THREAD

**Issue by xushaoxiao** [ovh/utask#374]
utask-utask-1  | wait-for-it.sh: db:5432 is available after 4 seconds
utask-utask-1  | time="2022-10-19T05:30:39Z" level=fatal msg="failed to run initialization plugin: unable to load configuration: configstore: get \"callback-config\": no item found"
utask-utask-1 exited with code 1

**Comment by rclsilver** [comment]
Hi, the bug has been fixed with this commit https://github.com/ovh/utask/commit/029bf5386680231bf0f0a828439d0eaba1989d83

Could you try to pull the latest version?

**Comment by rbeuque74** [comment]
Fixed by #363
