### ISSUE TITLE
Action plugin: script

### ISSUE THREAD

**Issue by loopfz** [ovh/utask#38]
Implement a plugin "script" that forks and executes a script within the utask container.

**Suggestion:**

```action:
    type: script
    configuration:
        file: check-invoice.py
        argv:
            - {{.step.getInvoice.output.invoiceID}}
            - ...
        stdin: foobar
        timeout: 5s
```

This should execute for the step the script **check-invoice.py**, which needs to be present in a configured _script folder_ within the utask container.
The script should be executable (+x), and use any interpreter as long as it is present in the utask container. The base utask image should maybe provide the most common interpreters?

There should be a way to pass data to the following steps in a structured way, it may adopt a similar strategy as the ssh plugin: the _last_ line of the script's stdout will be json parsed, and if it succeeds will be used as the result payload for the step.

**Comment by w3st3ry** [comment]
Merged #46
