### ISSUE TITLE
Captured loop variable inside a goroutine

### ISSUE THREAD

**Issue by DrRebus** [ovh/utask#480]
I'm sure it qualifies as bug so I opened a blank issue, but I noticed a weird usage of a loop variable captured in a goroutine at:  https://github.com/ovh/utask/blob/101b9974e03a6639f7cd6f5dc60d7d27713caa41/engine/engine.go#L706

When iterating over available steps, if a `foreach` step is followed by other steps (at least one), the last step will actually be pushed into the channel in place of the `foreach` step.

The `foreach` step should be run at some point, but as long as there is another step after it, it won't be run at all.

**Comment by rbeuque74** [comment]
Hello,
Thanks for the report, I opened a pull-request for that.
