### ISSUE TITLE
releasing: go-releaser should push install-utask.sh

### ISSUE THREAD

**Issue by rbeuque74** [ovh/utask#72]
When releasing a new version of utask, goreleaser is not pushing install-utask.sh, which breaks our installation procedure which is:
```sh
mkdir utask && cd utask
wget https://github.com/ovh/utask/releases/latest/download/install-utask.sh
sh install-utask.sh
docker-compose up
```

We should have a way to push this file automatically to the release, in order to avoid breaking while releasing.

**Comment by loopfz** [comment]
fixed
